language: ruby
cache: bundler
sudo: false

install:
  - gem install bundler
  - bundle install

script:
  - env bundle exec rake site:deploy

env:
  global:
    secure: EXAMPLE

after_success:
  - touch ./_site/.nojekyll




# deploy:
#   provider: pages
#   skip-cleanup: true
#   keep-history: true
#   on:
#     branch: master
#   github-token: $HE_Key_DEPLOY_TOKEN
#   local-dir: _site
#   committer-from-gh: true