language: ruby
cache: bundler
sudo: false

install:
  - gem install bundler
  - gem install octopress-autoprefixer
  - bundle install

script:
  - env JEKYLL_ENV=production bundle exec jekyll build

after_success:
  - touch ./_site/.nojekyll

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
  github-token: $GITHUB_TOKEN
  local-dir: _site
  committer-from-gh: true
