username: yilun1017
repo: yilun1017.github.io
branch: master



# Site/SEO settings
email: louyilun@126.com
permalink: /:year/:month/:day/:title/
google_analytics: 

title: "娄依伦"
description: "we can play multiple roles, play around!"
url: ""
baseurl: ""
twitter_username: 
default_img: 

# Profile settings
name: "Yilun"
profile_img:
  - https://i.loli.net/2020/09/23/dhxOC8pagW2sYwy.jpg
profile: 娄依伦<br>we can play multiple roles,<br> play around!<br>we can play multiple roles,<br> play around!<br>we can play multiple roles,<br> play around!
social: 
  - [qq, qq]
  - [twitter, twitter]
  - [weibo, weibo]
  - [facebook-f, facebook-f]
  - [linux, linux]
github: yilun1017.github.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - octopress-autoprefixer
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude: 
  - _screenshots
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - LICENSE.txt
  - README.md
  - .travis.yml
  - vendor

# Pagination
paginate: 5
paginate_path: "/blog/page-:num"

# Sass
sass:
  style: compressed
