# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: pages

on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install
    - name: Run a multi-line script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAGES }}
      run: |
        sudo apt install -y git

        git config --global url."https://".insteadOf git://
        git config --global url."https://github.com/".insteadOf git@github.com:
        git submodule update --init --recursive
        remote_repo="https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        remote_branch=master
        ls
        bundle exec jekyll build
        sudo rm -rf ./category
        echo "ssssssss"
        ls ./_site
        sudo cp -rf ./_site/category ./
        echo  "jahjahah"
        
        git init
        git config user.name "github-actions-bot"
        git config user.email "github-actions-bot@users.noreply.github.com"
        git add .
        git commit -m "Deploy GitHub Pages"
        git push --force "${remote_repo}" master:${remote_branch}
      
